(function() {
    /* Icon Maps */
    var maps = {
        "address-at": "0xe000",
        "alarm-clock": "0xe001",
        "alarm-clock-1": "0xe002",
        "alarm-clock-outline": "0xe003",
        "albums": "0xe004",
        "albums-outline": "0xe005",
        "android": "0xe006",
        "android-outine": "0xe007",
        "apple": "0xe008",
        "apple-outline": "0xe009",
        "archive": "0xe00a",
        "arrow-backward": "0xe00b",
        "arrow-down": "0xe00c",
        "arrow-down-1": "0xe00d",
        "arrow-down-left": "0xe00e",
        "arrow-down-right": "0xe00f",
        "arrow-graph-down-left": "0xe010",
        "arrow-graph-down-right": "0xe011",
        "arrow-graph-up-left": "0xe012",
        "arrow-graph-up-right": "0xe013",
        "arrow-left": "0xe014",
        "arrow-left-1": "0xe015",
        "arrow-line-down": "0xe016",
        "arrow-line-left": "0xe017",
        "arrow-line-right": "0xe018",
        "arrow-line-up": "0xe019",
        "arrow-move": "0xe01a",
        "arrow-right": "0xe01b",
        "arrow-right-1": "0xe01c",
        "arrow-up": "0xe01d",
        "arrow-up-1": "0xe01e",
        "arrow-up-left": "0xe01f",
        "arrow-up-right": "0xe020",
        "at-address": "0xe021",
        "at-address-thick": "0xe022",
        "back-system": "0xe023",
        "bag": "0xe024",
        "bar": "0xe025",
        "battery": "0xe026",
        "battery-charging": "0xe027",
        "battery-empty": "0xe028",
        "battery-full": "0xe029",
        "battery-low": "0xe02a",
        "battery-medium": "0xe02b",
        "beaker": "0xe02c",
        "beaker-science-flask": "0xe02d",
        "beer": "0xe02e",
        "bell": "0xe02f",
        "bell-alarm": "0xe030",
        "bell-outline": "0xe031",
        "bitcoin": "0xe032",
        "bitcoin-outline": "0xe033",
        "bluetooth": "0xe034",
        "book": "0xe035",
        "bookmark": "0xe036",
        "bookmark-1": "0xe037",
        "bookmark-outline": "0xe038",
        "box": "0xe039",
        "box-outline": "0xe03a",
        "briefcase": "0xe03b",
        "briefcase-2": "0xe03c",
        "briefcase-outline": "0xe03d",
        "brightness": "0xe03e",
        "brightness-outline": "0xe03f",
        "browsers": "0xe040",
        "browsers-outline": "0xe041",
        "bubbles": "0xe042",
        "buffer": "0xe043",
        "buffer-outline": "0xe044",
        "bug": "0xe045",
        "buoy-help": "0xe046",
        "calculator": "0xe047",
        "calculator-2": "0xe048",
        "calculator-outline": "0xe049",
        "calendar": "0xe04a",
        "calendar-2": "0xe04b",
        "calendar-3": "0xe04c",
        "calendar-outline": "0xe04d",
        "call": "0xe04e",
        "call-phone": "0xe04f",
        "call-phone-outline": "0xe050",
        "camera": "0xe051",
        "camera-2": "0xe052",
        "camera-3": "0xe053",
        "camera-outline": "0xe054",
        "car": "0xe055",
        "caret-down": "0xe056",
        "caret-left": "0xe057",
        "caret-right": "0xe058",
        "caret-up": "0xe059",
        "chat-talk": "0xe05a",
        "chat-talk-outline": "0xe05b",
        "chatbubble": "0xe05c",
        "chatbubble-outline": "0xe05d",
        "check-circle": "0xe05e",
        "check-mark": "0xe05f",
        "check-mark-2": "0xe060",
        "check-mark-3": "0xe061",
        "check-mark-4": "0xe062",
        "check-mark-circle": "0xe063",
        "check-mark-circle-outline": "0xe064",
        "chevron-down": "0xe065",
        "chevron-down-1": "0xe066",
        "chevron-left": "0xe067",
        "chevron-left-1": "0xe068",
        "chevron-left-thick": "0xe069",
        "chevron-right": "0xe06a",
        "chevron-right-1": "0xe06b",
        "chevron-right-thick": "0xe06c",
        "chevron-up": "0xe06d",
        "chevron-up-1": "0xe06e",
        "circle-filled": "0xe06f",
        "circle-filled-outline": "0xe070",
        "clipboard": "0xe071",
        "clock": "0xe072",
        "clock-2": "0xe073",
        "clock-2-outline": "0xe074",
        "clock-outline": "0xe075",
        "clock-time": "0xe076",
        "clock-time-outline": "0xe077",
        "close-circle": "0xe078",
        "close-circle-outline": "0xe079",
        "close-empty": "0xe07a",
        "cloud": "0xe07b",
        "cloud-2": "0xe07c",
        "cloud-download": "0xe07d",
        "cloud-download-outline": "0xe07e",
        "cloud-lightning": "0xe07f",
        "cloud-lightning-outline": "0xe080",
        "cloud-moon": "0xe081",
        "cloud-moon-outline": "0xe082",
        "cloud-outline": "0xe083",
        "cloud-rain": "0xe084",
        "cloud-rain-outline": "0xe085",
        "cloud-small": "0xe086",
        "cloud-small-outline": "0xe087",
        "cloud-sun": "0xe088",
        "cloud-sun-outline": "0xe089",
        "cloud-upload": "0xe08a",
        "cloud-upload-2": "0xe08b",
        "cloud-upload-outline": "0xe08c",
        "code": "0xe08d",
        "code-download": "0xe08e",
        "code-working": "0xe08f",
        "cog": "0xe090",
        "cog-outline": "0xe091",
        "compass": "0xe092",
        "compose": "0xe093",
        "compose-edit": "0xe094",
        "compose-edit-outline": "0xe095",
        "contacs": "0xe096",
        "contact": "0xe097",
        "contact-2": "0xe098",
        "contact-add": "0xe099",
        "contact-add-2": "0xe09a",
        "contact-add-3": "0xe09b",
        "contact-big": "0xe09c",
        "contact-group": "0xe09d",
        "contact-group-outline": "0xe09e",
        "contact-outline": "0xe09f",
        "contact-outline-add": "0xe0a0",
        "contacts": "0xe0a1",
        "contacts-social": "0xe0a2",
        "contrast": "0xe0a3",
        "copy": "0xe0a4",
        "copy-outline": "0xe0a5",
        "credit-card": "0xe0a6",
        "crosshairpinpoint": "0xe0a7",
        "cup-coffee": "0xe0a8",
        "data": "0xe0a9",
        "designernews": "0xe0aa",
        "designernews-outline": "0xe0ab",
        "disc": "0xe0ac",
        "display-contrast": "0xe0ad",
        "document": "0xe0ae",
        "download": "0xe0af",
        "download-inbox": "0xe0b0",
        "drag": "0xe0b1",
        "drag-2": "0xe0b2",
        "dribble": "0xe0b3",
        "dribble-outline": "0xe0b4",
        "dropbox": "0xe0b5",
        "dropbox-outline": "0xe0b6",
        "dropdown": "0xe0b7",
        "egg": "0xe0b8",
        "eject": "0xe0b9",
        "electric-flash-outline": "0xe0ba",
        "electric-no-off": "0xe0bb",
        "exclamation": "0xe0bc",
        "exclamation-alert": "0xe0bd",
        "eye-disabled": "0xe0be",
        "eye-glass": "0xe0bf",
        "eye-glass-outline": "0xe0c0",
        "eye-view": "0xe0c1",
        "eye-view-2": "0xe0c2",
        "eye-view-outline": "0xe0c3",
        "facebook": "0xe0c4",
        "facebook-outline": "0xe0c5",
        "fast-backward": "0xe0c6",
        "fast-forward": "0xe0c7",
        "fast-forward-1": "0xe0c8",
        "fast-forward-outline": "0xe0c9",
        "female": "0xe0ca",
        "female-symbol": "0xe0cb",
        "fighter": "0xe0cc",
        "file-document-text": "0xe0cd",
        "filing": "0xe0ce",
        "film-maker": "0xe0cf",
        "filmstrip": "0xe0d0",
        "filmstrip-outline": "0xe0d1",
        "flag": "0xe0d2",
        "flag-2": "0xe0d3",
        "flag-outline": "0xe0d4",
        "flash-electric": "0xe0d5",
        "flash-electric-2": "0xe0d6",
        "folder-open": "0xe0d7",
        "folder-open-2": "0xe0d8",
        "folder-small": "0xe0d9",
        "folder-small-outline": "0xe0da",
        "fork": "0xe0db",
        "fork-repo": "0xe0dc",
        "forward": "0xe0dd",
        "freebsd-devil": "0xe0de",
        "friends": "0xe0df",
        "gamepad": "0xe0e0",
        "gamepad-2": "0xe0e1",
        "gear-cog": "0xe0e2",
        "gear-setting": "0xe0e3",
        "gear-setting-1": "0xe0e4",
        "gear-setting-2": "0xe0e5",
        "gear-setting-2-1": "0xe0e6",
        "github": "0xe0e7",
        "github-outline": "0xe0e8",
        "glass-wine": "0xe0e9",
        "globe": "0xe0ea",
        "globe-outline": "0xe0eb",
        "globe-world": "0xe0ec",
        "globe-world-1": "0xe0ed",
        "googleplus": "0xe0ee",
        "googleplus-1": "0xe0ef",
        "googleplus-2": "0xe0f0",
        "googleplus-thick": "0xe0f1",
        "grid": "0xe0f2",
        "hackernews": "0xe0f3",
        "hackernews-outline": "0xe0f4",
        "hammer": "0xe0f5",
        "hand-block": "0xe0f6",
        "hand-like": "0xe0f7",
        "hand-unlike": "0xe0f8",
        "hashtag": "0xe0f9",
        "headphone": "0xe0fa",
        "heart": "0xe0fb",
        "heart-small": "0xe0fc",
        "heart-small-outline": "0xe0fd",
        "home": "0xe0fe",
        "home-system": "0xe0ff",
        "ice-cream": "0xe100",
        "inbox": "0xe101",
        "inbox-box": "0xe102",
        "inbox-outline": "0xe103",
        "infinite": "0xe104",
        "infinite-outline": "0xe105",
        "information": "0xe106",
        "information-circle": "0xe107",
        "information-circle-2": "0xe108",
        "information-small": "0xe109",
        "information-small-circle": "0xe10a",
        "information-small-circle-outline": "0xe10b",
        "ionic": "0xe10c",
        "ionic-outline": "0xe10d",
        "ipod": "0xe10e",
        "key": "0xe10f",
        "keypad": "0xe110",
        "keypad-2": "0xe111",
        "keypad-outline": "0xe112",
        "knife": "0xe113",
        "laptop": "0xe114",
        "leaf": "0xe115",
        "letter-mail": "0xe116",
        "lightbulb": "0xe117",
        "lightbulb-1": "0xe118",
        "lightbulb-2": "0xe119",
        "lightbulb-outline": "0xe11a",
        "link": "0xe11b",
        "linkedin": "0xe11c",
        "linkedin-outline": "0xe11d",
        "linux": "0xe11e",
        "loading-1": "0xe11f",
        "loading-2": "0xe120",
        "loading-3": "0xe121",
        "loading-4": "0xe122",
        "location": "0xe123",
        "lock": "0xe124",
        "lock-big": "0xe125",
        "lock-outline": "0xe126",
        "log-in": "0xe127",
        "log-out": "0xe128",
        "log-out-1": "0xe129",
        "loop": "0xe12a",
        "magnet": "0xe12b",
        "mail-letter": "0xe12c",
        "mail-letter-2": "0xe12d",
        "mail-letter-outline": "0xe12e",
        "mail-send": "0xe12f",
        "male": "0xe130",
        "male-symbol": "0xe131",
        "map": "0xe132",
        "mark-map": "0xe133",
        "mark-map-1": "0xe134",
        "mark-map-outline": "0xe135",
        "medkit": "0xe136",
        "medkit-2": "0xe137",
        "medkit-outline": "0xe138",
        "message-talk": "0xe139",
        "mic": "0xe13a",
        "mic-2": "0xe13b",
        "mic-3": "0xe13c",
        "mic-4": "0xe13d",
        "mic-5": "0xe13e",
        "mic-off": "0xe13f",
        "mic-outline": "0xe140",
        "minus": "0xe141",
        "minus-2": "0xe142",
        "minus-3": "0xe143",
        "minus-circle": "0xe144",
        "minus-circle-2": "0xe145",
        "minus-circle-outline": "0xe146",
        "minus-remove": "0xe147",
        "mixer": "0xe148",
        "mixer-2": "0xe149",
        "mobile-phone": "0xe14a",
        "moon": "0xe14b",
        "moon-outline": "0xe14c",
        "more": "0xe14d",
        "more-2": "0xe14e",
        "more-option": "0xe14f",
        "more-outline": "0xe150",
        "music-note": "0xe151",
        "music-note-2": "0xe152",
        "music-song": "0xe153",
        "navicon": "0xe154",
        "navround": "0xe155",
        "navigate": "0xe156",
        "navigate-location": "0xe157",
        "navigate-outline": "0xe158",
        "no-smoke": "0xe159",
        "note-file": "0xe15a",
        "nuclear": "0xe15b",
        "paper-airplane": "0xe15c",
        "paper-clip": "0xe15d",
        "parentheses": "0xe15e",
        "pause": "0xe15f",
        "pause-2": "0xe160",
        "pause-outline": "0xe161",
        "pencil-edit": "0xe162",
        "photo-image": "0xe163",
        "photo-picture": "0xe164",
        "photos": "0xe165",
        "photos-outline": "0xe166",
        "photos-pictures": "0xe167",
        "pie": "0xe168",
        "pie-2": "0xe169",
        "pie-outline": "0xe16a",
        "pin": "0xe16b",
        "pin-location": "0xe16c",
        "pinterest": "0xe16d",
        "pinterest-outline": "0xe16e",
        "pizza": "0xe16f",
        "plane-airport": "0xe170",
        "play": "0xe171",
        "play-2": "0xe172",
        "play-3": "0xe173",
        "play-outline": "0xe174",
        "play-station": "0xe175",
        "plus": "0xe176",
        "plus-add": "0xe177",
        "plus-add-2": "0xe178",
        "plus-big": "0xe179",
        "plus-circle": "0xe17a",
        "plus-circle-outline": "0xe17b",
        "plus-outline": "0xe17c",
        "power-off": "0xe17d",
        "print": "0xe17e",
        "print-1": "0xe17f",
        "print-2": "0xe180",
        "print-outline": "0xe181",
        "question": "0xe182",
        "question-circle": "0xe183",
        "question-circle-1": "0xe184",
        "question-circle-outline": "0xe185",
        "question-small": "0xe186",
        "quote": "0xe187",
        "radio-waves": "0xe188",
        "random": "0xe189",
        "record": "0xe18a",
        "record-2": "0xe18b",
        "record-outline": "0xe18c",
        "reddit": "0xe18d",
        "reddit-outline": "0xe18e",
        "redo": "0xe18f",
        "redo-outline": "0xe190",
        "refresh": "0xe191",
        "refresh-1": "0xe192",
        "refresh-circle": "0xe193",
        "refresh-circle-outline": "0xe194",
        "reload": "0xe195",
        "remove": "0xe196",
        "remove-delete": "0xe197",
        "remove-delete-circle": "0xe198",
        "remove-delete-two": "0xe199",
        "reply": "0xe19a",
        "reply-all": "0xe19b",
        "resize-arrow-2": "0xe19c",
        "resize-arrow-down": "0xe19d",
        "resize-arrow-up": "0xe19e",
        "return-left": "0xe19f",
        "return-left-1": "0xe1a0",
        "rewind": "0xe1a1",
        "rewind-outline": "0xe1a2",
        "rss": "0xe1a3",
        "rss-outline": "0xe1a4",
        "screen": "0xe1a5",
        "screen-1": "0xe1a6",
        "screen-outline": "0xe1a7",
        "search": "0xe1a8",
        "search-2": "0xe1a9",
        "search-3": "0xe1aa",
        "search-outline": "0xe1ab",
        "send-mail": "0xe1ac",
        "send-mail-outline": "0xe1ad",
        "setting-tools": "0xe1ae",
        "share": "0xe1af",
        "shopping-cart": "0xe1b0",
        "shopping-cart-outline": "0xe1b1",
        "signal-bar": "0xe1b2",
        "signal-wifi": "0xe1b3",
        "skipbackward": "0xe1b4",
        "skipbackward-outline": "0xe1b5",
        "skipforward": "0xe1b6",
        "skipforward-outline": "0xe1b7",
        "skype": "0xe1b8",
        "skype-outline": "0xe1b9",
        "snowy": "0xe1ba",
        "sort": "0xe1bb",
        "speaker": "0xe1bc",
        "speaker-no": "0xe1bd",
        "speakerphone": "0xe1be",
        "speedometer": "0xe1bf",
        "speedometer-1": "0xe1c0",
        "speedometer-outline": "0xe1c1",
        "spoon": "0xe1c2",
        "square-download": "0xe1c3",
        "square-download-outline": "0xe1c4",
        "square-upload": "0xe1c5",
        "square-upload-outline": "0xe1c6",
        "star": "0xe1c7",
        "star-1": "0xe1c8",
        "star-2": "0xe1c9",
        "star-outline": "0xe1ca",
        "steam": "0xe1cb",
        "stop": "0xe1cc",
        "stopwatch": "0xe1cd",
        "stopwatch-1": "0xe1ce",
        "stopwatch-outline": "0xe1cf",
        "storage": "0xe1d0",
        "swap-exchage": "0xe1d1",
        "tablet": "0xe1d2",
        "tag": "0xe1d3",
        "tag-outline": "0xe1d4",
        "tag-round": "0xe1d5",
        "tags": "0xe1d6",
        "tags-round": "0xe1d7",
        "talk-chat": "0xe1d8",
        "talk-chat-1": "0xe1d9",
        "talk-chat-bubble": "0xe1da",
        "talk-chat-bubble-1": "0xe1db",
        "talk-chat-bubble-2": "0xe1dc",
        "thermometer": "0xe1dd",
        "timer": "0xe1de",
        "timer-clock": "0xe1df",
        "timer-clock-outline": "0xe1e0",
        "trash-bin": "0xe1e1",
        "trash-bin-1": "0xe1e2",
        "trash-bin-2": "0xe1e3",
        "trash-bin-2-1": "0xe1e4",
        "trash-bin-outline": "0xe1e5",
        "tumblr": "0xe1e6",
        "tumblr-outline": "0xe1e7",
        "twitter": "0xe1e8",
        "twitter-outline": "0xe1e9",
        "umbrella": "0xe1ea",
        "undo": "0xe1eb",
        "undo-outline": "0xe1ec",
        "unlock": "0xe1ed",
        "unlock-2": "0xe1ee",
        "unlock-outline": "0xe1ef",
        "usb": "0xe1f0",
        "user": "0xe1f1",
        "user-circle": "0xe1f2",
        "user-circle-outline": "0xe1f3",
        "video-camera": "0xe1f4",
        "video-camera-outline": "0xe1f5",
        "videocamera": "0xe1f6",
        "vimeo": "0xe1f7",
        "vimeo-outline": "0xe1f8",
        "volume-high": "0xe1f9",
        "volume-low": "0xe1fa",
        "volume-medium": "0xe1fb",
        "volume-mute": "0xe1fc",
        "volume-speaker": "0xe1fd",
        "waterdrop": "0xe1fe",
        "wifi": "0xe1ff",
        "windows": "0xe200",
        "windows-outline": "0xe201",
        "windows-system": "0xe202",
        "wine-glass": "0xe203",
        "wine-glass-outline": "0xe204",
        "wordpress": "0xe205",
        "wordpress-outline": "0xe206",
        "wrench": "0xe207",
        "xbox": "0xe208",
        "yahoo": "0xe209",
        "yahoo-outline": "0xe20a",
        "youtube-play": "0xe20b",
        "youtube-play-outline": "0xe20c",
    };

    /* Data Icon List */
    var DataIcons = function() {
        this.icons = {};

        return this;
    };

    /* Data Icon Prototypes */
    DataIcons.prototype = {
        push: function(name, value) {
            var $this = this;

            if ('string' == typeof name && 'string' == typeof value) {
                $this.icons[name] = value;
            }

            else if ('object' == typeof name && !name.length) {
                for (var key in name) {
                    if (name.hasOwnProperty(key)) {
                        this.icons[key] = name[key];
                    }
                }
            }

            return this;
        },
        exist: function(name) {
            if (name in this.icons) {
                return true;
            }
            else {
                return false;
            }
        },
        get: function(name) {
            if (name in this.icons) {
                return this.icons[name];
            }
        }
    };

    /* Data Icon Provider */
    var ionicon = angular.module('IonIcon', []);

    ionicon.factory('$ionIcon', function() {

        /* Creating New DataIcon */
        var dataIcon = new DataIcons();

        /* Registering icons */
        for (var key in maps) {
            if (maps.hasOwnProperty(key)) {
                /* Convert the value to PUA char and push it */
                dataIcon.push(key, String.fromCharCode(maps[key]));
            }
        }

        /* Return DataIcon */
        return dataIcon;
    });

    /* Dynamic Icon Directive - :before */
    ionicon.directive('icon', ['$timeout', '$ionIcon', function($timeout, $ionIcon) {
        return {
            link: function(scope, element, attrs) {
                $timeout(function() {
                    var icon = element.attr('icon');

                    if (icon && $ionIcon.exist(icon)) {
                        element.attr('icon', $ionIcon.get(icon)).addClass('ready');
                    }
                });
            }
        }
    }]);

    /* Dynamic Icon Directive - :after */
    ionicon.directive('iconA', ['$timeout', '$ionIcon', function($timeout, $ionIcon) {
        return {
            link: function(scope, element, attrs) {
                $timeout(function() {
                    var icon = element.attr('icon-a');

                    if (icon && $ionIcon.exist(icon)) {
                        element.attr('icon-a', $ionIcon.get(icon)).addClass('ready');
                    }
                });
            }
        }
    }]);
})();
